package:
  format-version: "1.0.0"
  name: "core_apps_pic32wm_bw1"
  type: "application"
  status: "production"
  required: false
  version: "v1.0.0"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "dev"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
    - name: "core"
      type: "package"
      version: "dev"
