package:
  format-version: "1.0.0"
  name: "core_apps_pic32wm_bw1"
  type: "application"
  status: "production"
  required: false
  version: "v1.0.0"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.15.5"
